import { CommentPreset, PresetAvatar } from '../types';

export const AVATAR_PRESETS: PresetAvatar[] = [
  {
    id: 'tokcomment-user',
    name: 'Suit Professional (from Screenshot)',
    category: 'creators',
    url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=240&auto=format&fit=crop&q=80',
  },
  {
    id: 'creator-1',
    name: 'TikTok Creator',
    category: 'creators',
    url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'creator-2',
    name: 'Brand Official',
    category: 'creators',
    url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'girl-1',
    name: 'Chloe',
    category: 'girls',
    url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'girl-2',
    name: 'Mia',
    category: 'girls',
    url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'girl-3',
    name: 'Jessica',
    category: 'girls',
    url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'guy-1',
    name: 'Alex',
    category: 'guys',
    url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'guy-2',
    name: 'David',
    category: 'guys',
    url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'guy-3',
    name: 'Mark Rider',
    category: 'guys',
    url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'meme-1',
    name: 'Cute Cat',
    category: 'memes',
    url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=200&auto=format&fit=crop&q=80',
  },
  {
    id: 'meme-2',
    name: 'Anime PFP',
    category: 'memes',
    url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&auto=format&fit=crop&q=80',
  },
];

export const COMMENT_PRESETS: CommentPreset[] = [
  {
    title: 'Reply Bubble (TokComment Style)',
    category: 'TokComment Reply',
    name: 'username',
    username: 'username',
    commentText: 'Write any comment and see what happens 😊',
    likes: '14.2K',
    timestamp: '2h ago',
    isVerified: false,
    likedByCreator: false,
    pinned: false,
  },
  {
    title: 'NMAX Giveaway Winner / Disclaimer',
    category: 'Promo & Giveaways',
    name: 'Mark Joshua Official',
    username: 'markjosh_munti',
    commentText: 'Legit ba talaga yung NMAX 155 winner sa Muntinlupa? Pa-update naman if na-claim na yung unit please!! 🛵🔥🙏',
    likes: '42.8K',
    timestamp: '2h ago',
    isVerified: true,
    likedByCreator: true,
    pinned: true,
  },
  {
    title: 'UGC Product Question (TikTok Shop)',
    category: 'UGC & Sales',
    name: 'Sarah 🌸',
    username: 'sarah_lifestyle',
    commentText: 'Where did you get that?? Drop the link please I need this for my room right now!! 😭❤️',
    likes: '18.4K',
    timestamp: '5h ago',
    isVerified: false,
    likedByCreator: true,
  },
  {
    title: 'Viral Troll / Skepticism',
    category: 'Viral Drama',
    name: 'Bro Is Not Real',
    username: 'itsreallyhim99',
    commentText: 'Bro thought we wouldn’t notice the cut at 0:04 💀💀💀',
    likes: '89.2K',
    timestamp: '1d ago',
    isVerified: false,
    likedByCreator: false,
  },
  {
    title: 'Wholesome Compliment',
    category: 'General',
    name: 'Elena Rostova',
    username: 'elena_vibe',
    commentText: 'The quality of your videos is unmatched! Please make a tutorial on this! ✨✨',
    likes: '7,314',
    timestamp: '3h ago',
    isVerified: false,
    likedByCreator: true,
  },
  {
    title: 'Official Winner Claimed Notice',
    category: 'Promo & Giveaways',
    name: 'Promo Coordinator',
    username: 'promoofficial_ph',
    commentText: 'DISCLAIMER: Congratulations to our official Muntinlupa NMAX Winner! Draw conducted with DTI permit. Ride safe po! 🛵🎉',
    likes: '31.5K',
    timestamp: '1d ago',
    isVerified: true,
    isCreator: true,
    pinned: true,
    likedByCreator: true,
  },
  {
    title: 'Part 2 Request',
    category: 'Viral',
    name: 'Random Scroller',
    username: 'user948172948',
    commentText: 'DROP PART 2 PLEASE DON’T LEAVE US ON A CLIFFHANGER 😭😭',
    likes: '54.1K',
    timestamp: '7h ago',
    isVerified: false,
    likedByCreator: false,
  },
];

export const EMOJI_LIST = [
  '😂', '😭', '💀', '🔥', '❤️', '✨', '🥺', '😳', 
  '🙏', '🛵', '🏍️', '💯', '😍', '👀', '🎉', '👏', 
  '🙌', '🤩', '🎁', '🚀', '⭐', '🤤', '🤫', '🤣'
];
